name: Collectors

on:
  schedule:
    - cron: "0 */3 * * *"   # Telegram: every 3 hours (UTC)
    - cron: "0 6 * * *"     # Facebook: daily 06:00 UTC
  workflow_dispatch: {}

jobs:
  telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps for collectors (Telegram)
        run: |
          pip install --upgrade pip
          pip install telethon pandas requests

      - name: Run Telegram collector (script)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_STRING_SESSION: ${{ secrets.TELEGRAM_STRING_SESSION }}
          TG_CHANNELS: "dmski_1,akbardrwz,Druzeresistance"
          TG_MAX_POSTS: "200"
          TG_PREFILTER: "السويداء,الساحل,اللاذقية,طرطوس,قتل,اشتباك,طائفي"
        run: python collectors/telegram_collector.py

  facebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps for Facebook collector
        run: |
          pip install --upgrade pip
          pip install facebook-scraper pandas requests lxml_html_clean

      - name: Run Facebook collector (script)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          FB_PAGES: "https://www.facebook.com/Suwayda24,https://www.facebook.com/groups/zero0nine9"
          FB_LIMIT: "200"
          FB_USER_AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
          FB_COOKIES_JSON: ${{ secrets.FB_COOKIES_JSON }}
        run: python collectors/facebook_collector.py
